# Generated by Django 5.1.6 on 2025-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('User', 'User'), ('Supervisor', 'Supervisor')], default='User', max_length=20),
        ),
    ]
