# Generated by Django 5.1.6 on 2025-03-15 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0003_alter_contract_contract_type_alter_contract_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
    ]
